# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191112_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('refunded', 'Возвращен')], default='created', max_length=120, verbose_name='Статус'),
        ),
    ]
