# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181112_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slag',
            field=models.SlugField(blank=True),
        ),
    ]
